# Generated by Django 6.0.4 on 2026-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_order_razorpay_signature_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('onlinepayment', 'Online Payment'), ('wallet', 'Wallet')], default='cod', max_length=20),
        ),
    ]
